#!/usr/bin/env python3


import os
from total_connect_comfort import client


username = os.environ.get('username')
password = os.environ.get('password')
c = client.Client(username, password)
data = c.locations()


devices = []


for location in data:
	for device in location['Devices']:
		info = {
			'id': str(device['DeviceID']),
			'label': device['Name'],
			'temp': device['ThermostatData']['IndoorTemperature'],
			'setpoint': device['ThermostatData']['ScheduleHeatSp'],
			'units': 'F' if device['ThermostatData']['DisplayUnits']==1 else 'C'
		}
		devices.append(info)

print("graph_args --base 1000")
print("graph_title Honeywell Thermostats")
print("graph_vlabel degrees")
print("graph_category sensors")
for device in devices:
	name = 'id%s' % (device['id'],)
	print("%s.label %s" % (name, device['label']))
	print("%s.value %s" % (name, device['temp']))
	print("%s_setpt.label %s Setpoint" % (name, device['label']))
	print("%s_setpt.value %s" % (name, device['setpoint']))
